const stats = {
    power: 'Puissance Instantanée',
    consumption: 'Consommation',
    exposure: 'Exposition',
    dimming: 'Atténuation Lumineuse',
    temperature: 'Température',
    perceived_temperature: 'Température Ressentie',
    humidity: 'Humidité',
    occupancy: 'Fréquentation',
    acoustic_pressure: 'Niveau Sonore',
    uv: 'Indice UV',
    irrigation: 'Irrigation',
    irrigation_time: 'Temps Irrigation',
    operating_time: 'Temps de fonctionnement',
    commissioning_date: 'Date de début de suivi',
    last_location: 'Dernier emplacement',
    sound_level: 'Niveau Sonore',
    noise_nuisance: 'Nuisance Sonore',
    irrigation_time: 'temps irrigation',
    frequentation: 'fréquentation',
    occupancy: 'Fréquentation',
    PM_0_3: 'PM 0,3',
    PM_0_5: 'PM 0,5',
    PM_1: 'PM 1',
    PM_2_5: 'PM 2,5',
    PM_5: 'PM 5',
    PM_10: 'PM 10',
    PMCR_0_3: 'PMCR 0,3',
    PMCR_0_5: 'PMCR 0,5',
    PMCR_1: 'PMCR 1',
    PMCR_2_5: 'PMCR 2,5',
    PMCR_5: 'PMCR 5',
    voc: 'COV',
    co2: 'CO2',
    iaqi: 'Indice Qualité Air',
    viralRisk: 'Risque Viral',
    heartbeat: 'Fréquence cardiaque',
    respiration: 'Réspiration',
    activity: 'Activité',
    noise: 'Bruit',
    luminosity: 'Luminosité',
    air_treatment: "Traitement de l'Air",
};

export const measurementKeys = [
    { value: "", icon: "", key: "Sensor_PM10_1_Weight", name: "Sensor PM10 1 Weight" },
    { value: "", icon: "", key: "Sensor_PM10_2_5_Weight", name: "Sensor PM10 2 5 Weight" },
    { value: "", icon: "", key: "Sensor_PM10_10_Weight", name: "Sensor PM10 10 Weight" },
    { value: "", icon: "", key: "Sensor_PM60_1_Weight", name: "Sensor PM60 1 Weight" },
    { value: "", icon: "", key: "Sensor_PM60_2_5_Weight", name: "Sensor PM60 2 5 Weight" },
    { value: "", icon: "", key: "Sensor_PM60_10_Weight", name: "Sensor PM60 10 Weight" },
    { value: "", icon: "", key: "Sensor_PM900_1_Weight", name: "Sensor PM900 1 Weight" },
    {
        value: "", icon: "",
        key: "Sensor_PM900_2_5_Weight",
        name: "Sensor PM900 2 5 Weight",
    },
    { value: "", icon: "", key: "Sensor_PM900_10_Weight", name: "Sensor PM900 10 Weight" },
    {
        value: "", icon: "",
        key: "Sensor_PM_Measuring_Unit",
        name: "Sensor PM Measuring Unit",
    },
    {
        value: "", icon: "",
        key: "Internal_Temperature",
        name: "Internal temperature",
        unit: "°C",
    },
    {
        value: "", icon: "",
        key: "Restarted",
        name: "Restarted",
    },
    {
        value: "", icon: "",
        key: "Sensor_Firmware_Version",
        name: "Sensor Firmware Version",
    },
    {
        value: "", icon: "",
        key: "Comm_State",
        name: "Comm state",
    },

    { value: "", icon: "", key: "Sensor_Humidity", name: "Sensor Humidity", unit: "%" },
    { value: "", icon: "", key: "Sensor_Temperature", name: "Sensor Temperature", unit: "°C" },
    { value: "", icon: "", key: "humidity", name: "Humidity", unit: "%" },
    { value: "", icon: "", key: "temperature", name: "Temperature", unit: "°C" },
    { value: "", icon: "", key: "exposure", name: "Exposure" },
    { value: "", icon: "", key: "pm1", name: "PM 1", unit: "µg/㎥" },
    { value: "", icon: "", key: "pm2_5", name: "PM 2,5", unit: "µg/㎥" },
    { value: "", icon: "", key: "pm10", name: "PM 10", unit: "µg/㎥" },
    { value: "", icon: "", key: "pm0_3", name: "PM 0,3", unit: "µg/㎥" },
    { value: "", icon: "", key: "pm0_5", name: "PM 0,5", unit: "µg/㎥" },
    {
        value: "", icon: "",
        key: "PMCR_1",
        name: "PMCR 1",
    },
    {
        value: "", icon: "",
        key: "PMCR_2_5",
        name: "PMCR 2,5",
    },
    {
        value: "", icon: "",
        key: "noise",
        name: "Noise",
        unit: "dB",
    },
    { value: "", icon: "", key: "PMCR_5", name: "PMCR 5" },
    { value: "", icon: "", key: "acousticPressure", name: "Acoustic Pressure" },
    { value: "", icon: "", key: "frequentation", name: "Frequentation" },
    { value: "", icon: "", key: "occupancy", name: "Occupancy" },
    { value: "", icon: "", key: "battery", name: "Battery", unit: "%", },
    { value: "", icon: "", key: "tilt", name: "Tilt" },
    { value: "", icon: "", key: "irrigation", name: "Irrigation" },
    { value: "", icon: "", key: "activity", name: "Activity" },
    { value: "", icon: "", key: "respiration", name: "Respiration" },
    { value: "", icon: "", key: "heartbeat", name: "Heartbeat" },
    { value: "", icon: "", key: "falldown", name: "Falldown" },
    { value: "", icon: "", key: "rssi", name: "Rssi" },
    { value: "", icon: "", key: "uv", name: "UV" },
    { value: "", icon: "", key: "co2", name: "CO2", unit: "ppm" },
    { value: "", icon: "", key: "voc", name: "COV", unit: "μg/m³" },
    { value: "", icon: "", key: "iaqi", name: "Air Quality Index", unit: "/5" },
    { value: "", icon: "", key: "viralRisk", name: "Viral Risk" },
    { value: "", icon: "", key: "power", name: "Power" },
    { value: "", icon: "", key: "valve", name: "Valve" },
    { value: "", icon: "", key: "tamper", name: "Tamper" },
    { value: "", icon: "", key: "overload", name: "Overload" },
    { value: "", icon: "", key: "underrange", name: "Underrage" },
    { value: "", icon: "", key: "vBat", name: "V Bat" },
    { value: "", icon: "", key: "pressure", name: "Pressure" },
    { value: "", icon: "", key: "maximumNoise", name: "Maximum Noise", unit: "dB" },
    { value: "", icon: "", key: "averageNoise", name: "Noise", unit: "dB" },
];